; Play a little tune.
; Adapted from Simon's original to be
; less dependent on macro expansion

; Notes
C_	.equ	1
Cs	.equ	2
D_	.equ	3
Ds	.equ	4
E_	.equ	5
F_	.equ	6
Fs	.equ	7
G_	.equ	8
Gs	.equ	9
A_	.equ	10
As	.equ	11
B_	.equ	12

; Octaves
O1	.equ	0*12
O2	.equ	1*12
O3	.equ	2*12
O4	.equ	3*12
O5	.equ	4*12
O6	.equ	5*12
O7	.equ	6*12
O8	.equ	7*12

; Rest
quiet	.equ	0

zix
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	A_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	A_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	A_+O3, A_+O4
	.byte	D_+O4, D_+O5
	.byte	D_+O4, D_+O5
	.byte	G_+O4, G_+O5
	.byte	G_+O4, G_+O5
	.byte	C_+O5, C_+O6
	.byte	C_+O5, C_+O6
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	D_+O4, D_+O4
	.byte	D_+O4, D_+O4
	.byte	D_+O4, quiet
	.byte	D_+O4, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	A_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	A_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	A_+O5, A_+O4
	.byte	A_+O5, A_+O4
	.byte	G_+O5, G_+O6
	.byte	G_+O5, G_+O6
	.byte	E_+O5, E_+O6
	.byte	E_+O5, E_+O6
	.byte	D_+O5, D_+O6
	.byte	D_+O5, D_+O6
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	D_+O3, D_+O3
	.byte	D_+O3, D_+O3
	.byte	D_+O3, D_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, quiet
	.byte	G_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, quiet
	.byte	G_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	quiet, G_+O3
	.byte	quiet, G_+O3
	.byte	G_+O4, G_+O5
	.byte	G_+O4, G_+O5
	.byte	C_+O4, C_+O5
	.byte	C_+O4, C_+O5
	.byte	F_+O4, F_+O5
	.byte	F_+O4, F_+O5
	.byte	C_+O5, C_+O6
	.byte	C_+O5, C_+O6
	.byte	F_+O6, F_+O7
	.byte	F_+O6, F_+O7
	.byte	E_+O6, E_+O7
	.byte	E_+O6, E_+O7
	.byte	C_+O6, C_+O7
	.byte	C_+O6, C_+O7
	.byte	A_+O5, A_+O6
	.byte	A_+O5, A_+O6
	.byte	F_+O3, F_+O3
	.byte	F_+O3, F_+O3
	.byte	F_+O3, quiet
	.byte	F_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O4, F_+O4
	.byte	F_+O4, F_+O4
	.byte	F_+O4, quiet
	.byte	F_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O3, F_+O3
	.byte	F_+O3, F_+O3
	.byte	quiet, F_+O3
	.byte	quiet, F_+O3
	.byte	F_+O4, F_+O4
	.byte	F_+O4, F_+O4
	.byte	F_+O4, F_+O4
	.byte	F_+O4, F_+O4
	.byte	quiet, D_+O4
	.byte	quiet, D_+O4
	.byte	quiet, D_+O4
	.byte	quiet, D_+O4
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, quiet
	.byte	G_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O3, F_+O3
	.byte	F_+O3, F_+O3
	.byte	quiet, F_+O3
	.byte	quiet, F_+O3
	.byte	G_+O7, F_+O4
	.byte	quiet, F_+O4
	.byte	F_+O7, F_+O4
	.byte	quiet, F_+O4
	.byte	E_+O7, F_+O4
	.byte	quiet, G_+O7
	.byte	C_+O7, quiet
	.byte	quiet, F_+O7
	.byte	C_+O6, quiet
	.byte	quiet, E_+O7
	.byte	G_+O5, quiet
	.byte	quiet, C_+O7
	.byte	F_+O5, D_+O7
	.byte	quiet, G_+O6
	.byte	G_+O5, A_+O6
	.byte	quiet, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	A_+O3, E_+O7
	.byte	A_+O3, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, quiet
	.byte	As+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	A_+O3, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, quiet
	.byte	A_+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	G_+O4, E_+O5
	.byte	G_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	D_+O4, D_+O7
	.byte	D_+O4, G_+O6
	.byte	D_+O4, A_+O6
	.byte	D_+O4, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	A_+O3, E_+O7
	.byte	A_+O3, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, quiet
	.byte	As+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, quiet
	.byte	A_+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O5
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	D_+O3, D_+O5
	.byte	D_+O3, quiet
	.byte	D_+O3, A_+O4
	.byte	D_+O3, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	A_+O3, E_+O7
	.byte	A_+O3, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, quiet
	.byte	As+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	A_+O3, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, quiet
	.byte	A_+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	G_+O4, E_+O5
	.byte	G_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	D_+O4, D_+O7
	.byte	D_+O4, G_+O6
	.byte	D_+O4, A_+O6
	.byte	D_+O4, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	A_+O3, E_+O7
	.byte	A_+O3, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, quiet
	.byte	As+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O4, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O5
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O6, quiet
	.byte	A_+O6, A_+O5
	.byte	D_+O6, A_+O5
	.byte	E_+O6, D_+O5
	.byte	A_+O5, E_+O5
	.byte	D_+O6, A_+O4
	.byte	E_+O5, D_+O5
	.byte	A_+O5, E_+O4
	.byte	D_+O5, A_+O4
	.byte	E_+O5, D_+O4
	.byte	A_+O4, E_+O4
	.byte	D_+O5, A_+O3
	.byte	A_+O4, D_+O4
	.byte	D_+O4, A_+O3
	.byte	E_+O4, D_+O3
	.byte	A_+O3, E_+O3
	.byte	G_+O3, G_+O7
	.byte	G_+O3, C_+O7
	.byte	G_+O3, D_+O7
	.byte	quiet, G_+O6
	.byte	quiet, B_+O6
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, D_+O5
	.byte	G_+O4, quiet
	.byte	G_+O4, G_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	quiet, quiet
	.byte	G_+O3, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, D_+O4
	.byte	quiet, quiet
	.byte	G_+O5, D_+O5
	.byte	G_+O5, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, D_+O4
	.byte	G_+O3, quiet
	.byte	G_+O3, G_+O4
	.byte	quiet, quiet
	.byte	quiet, G_+O3
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, D_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O5
	.byte	quiet, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O5, D_+O4
	.byte	G_+O5, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O3
	.byte	G_+O4, quiet
	.byte	G_+O3, D_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O4
	.byte	quiet, quiet
	.byte	G_+O5, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, D_+O5
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	quiet, quiet
	.byte	C_+O5, D_+O7
	.byte	quiet, G_+O6
	.byte	C_+O5, A_+O6
	.byte	quiet, quiet
	.byte	F_+O3, F_+O7
	.byte	F_+O3, A_+O6
	.byte	F_+O3, C_+O7
	.byte	quiet, F_+O6
	.byte	quiet, G_+O6
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	F_+O4, D_+O5
	.byte	F_+O4, quiet
	.byte	F_+O4, G_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	F_+O3, G_+O3
	.byte	F_+O3, quiet
	.byte	F_+O3, D_+O4
	.byte	F_+O3, quiet
	.byte	F_+O4, G_+O4
	.byte	F_+O4, quiet
	.byte	F_+O4, D_+O4
	.byte	quiet, quiet
	.byte	F_+O5, D_+O5
	.byte	F_+O5, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O7
	.byte	G_+O3, C_+O7
	.byte	G_+O3, D_+O7
	.byte	quiet, G_+O6
	.byte	quiet, B_+O6
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, D_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O5
	.byte	quiet, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	F_+O3, D_+O4
	.byte	F_+O3, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	quiet, G_+O7
	.byte	quiet, quiet
	.byte	quiet, F_+O7
	.byte	quiet, quiet
	.byte	quiet, D_+O7
	.byte	quiet, quiet
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	C_+O5, G_+O6
	.byte	B_+O4, quiet
	.byte	As+O4, F_+O6
	.byte	A_+O4, quiet
	.byte	Gs+O4, D_+O6
	.byte	G_+O4, quiet
	.byte	Fs+O4, C_+O6
	.byte	F_+O4, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	A_+O3, E_+O7
	.byte	quiet, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, E_+O4
	.byte	A_+O4, E_+O6
	.byte	A_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	A_+O3, E_+O5
	.byte	A_+O3, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	As+O3, As+O4
	.byte	quiet, quiet
	.byte	D_+O4, D_+O5
	.byte	quiet, quiet
	.byte	G_+O4, G_+O5
	.byte	quiet, quiet
	.byte	C_+O5, C_+O6
	.byte	quiet, quiet
	.byte	C_+O4, E_+O6
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	quiet, E_+O7
	.byte	quiet, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O6
	.byte	A_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O5, A_+O3
	.byte	A_+O5, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O5, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O5
	.byte	A_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	D_+O4, D_+O5
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	A_+O3, E_+O7
	.byte	quiet, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, E_+O4
	.byte	A_+O4, E_+O6
	.byte	A_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	A_+O3, E_+O5
	.byte	A_+O3, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	As+O4, Fs+O5
	.byte	quiet, quiet
	.byte	D_+O5, As+O5
	.byte	quiet, quiet
	.byte	G_+O5, Ds+O6
	.byte	quiet, quiet
	.byte	C_+O6, Gs+O6
	.byte	quiet, quiet
	.byte	D_+O6, As+O6
	.byte	quiet, quiet
	.byte	F_+O6, Cs+O7
	.byte	quiet, quiet
	.byte	As+O6, Fs+O7
	.byte	quiet, quiet
	.byte	D_+O7, As+O7
	.byte	quiet, quiet
	.byte	A_+O3, A_+O7
	.byte	A_+O3, D_+O7
	.byte	quiet, E_+O7
	.byte	quiet, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, E_+O6
	.byte	A_+O4, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, E_+O4
	.byte	quiet, quiet
	.byte	quiet, E_+O6
	.byte	quiet, quiet
	.byte	A_+O3, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, E_+O4
	.byte	A_+O3, quiet
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	A_+O3, quiet
	.byte	As+O3, quiet
	.byte	B_+O3, quiet
	.byte	C_+O4, quiet
	.byte	Cs+O4, quiet
	.byte	D_+O4, quiet
	.byte	Ds+O4, quiet
	.byte	E_+O4, quiet
	.byte	F_+O4, F_+O4
	.byte	Fs+O4, Fs+O4
	.byte	G_+O4, G_+O4
	.byte	Gs+O4, Gs+O4
	.byte	A_+O4, A_+O4
	.byte	As+O4, As+O4
	.byte	B_+O4, B_+O4
	.byte	C_+O5, C_+O5
	.byte	G_+O3, G_+O7
	.byte	G_+O3, C_+O7
	.byte	G_+O3, D_+O7
	.byte	G_+O3, G_+O6
	.byte	quiet, B_+O6
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, D_+O6
	.byte	G_+O4, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	G_+O3, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, D_+O4
	.byte	G_+O3, quiet
	.byte	G_+O5, D_+O6
	.byte	G_+O5, quiet
	.byte	G_+O4, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, D_+O4
	.byte	G_+O3, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	quiet, G_+O3
	.byte	quiet, quiet
	.byte	G_+O3, D_+O4
	.byte	G_+O3, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O6
	.byte	quiet, quiet
	.byte	G_+O3, G_+O4
	.byte	quiet, quiet
	.byte	G_+O5, D_+O4
	.byte	G_+O5, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O3
	.byte	G_+O4, quiet
	.byte	G_+O3, D_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O4
	.byte	quiet, quiet
	.byte	G_+O5, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, D_+O6
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	quiet, quiet
	.byte	C_+O5, D_+O7
	.byte	quiet, G_+O6
	.byte	C_+O5, A_+O6
	.byte	quiet, quiet
	.byte	F_+O3, F_+O7
	.byte	F_+O3, A_+O6
	.byte	quiet, C_+O7
	.byte	quiet, F_+O6
	.byte	quiet, G_+O6
	.byte	quiet, quiet
	.byte	F_+O3, D_+O4
	.byte	quiet, quiet
	.byte	F_+O5, D_+O6
	.byte	F_+O5, quiet
	.byte	F_+O5, G_+O4
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	F_+O4, G_+O4
	.byte	F_+O4, quiet
	.byte	F_+O3, G_+O3
	.byte	F_+O3, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	F_+O4, G_+O4
	.byte	F_+O4, quiet
	.byte	F_+O4, D_+O4
	.byte	F_+O4, quiet
	.byte	F_+O5, D_+O6
	.byte	F_+O5, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	G_+O3, G_+O7
	.byte	G_+O3, C_+O7
	.byte	G_+O3, D_+O7
	.byte	G_+O3, G_+O6
	.byte	quiet, B_+O6
	.byte	quiet, quiet
	.byte	quiet, D_+O4
	.byte	quiet, quiet
	.byte	G_+O4, G_+O4
	.byte	G_+O4, quiet
	.byte	G_+O4, D_+O4
	.byte	G_+O4, quiet
	.byte	quiet, D_+O6
	.byte	quiet, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	F_+O4, D_+O4
	.byte	F_+O4, quiet
	.byte	quiet, G_+O4
	.byte	quiet, quiet
	.byte	Fs+O8, Fs+O8
	.byte	quiet, quiet
	.byte	F_+O8, F_+O8
	.byte	quiet, quiet
	.byte	D_+O8, D_+O8
	.byte	quiet, quiet
	.byte	C_+O8, C_+O8
	.byte	quiet, quiet
	.byte	C_+O5, G_+O7
	.byte	B_+O4, quiet
	.byte	As+O4, F_+O7
	.byte	A_+O4, quiet
	.byte	Gs+O4, D_+O7
	.byte	G_+O4, quiet
	.byte	Fs+O4, C_+O7
	.byte	F_+O4, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O4, D_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, quiet
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, As+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, quiet
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, quiet
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, quiet
	.byte	As+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, quiet
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, As+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, D_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, quiet
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, As+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, quiet
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, quiet
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, quiet
	.byte	As+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, quiet
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, As+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	quiet, G_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, G_+O3
	.byte	quiet, G_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	quiet, G_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	G_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	G_+O3, G_+O3
	.byte	quiet, G_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O3
	.byte	G_+O5, G_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	G_+O3, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	quiet, A_+O3
	.byte	F_+O5, A_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, A_+O3
	.byte	quiet, A_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O3, A_+O3
	.byte	quiet, A_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	A_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, A_+O3
	.byte	quiet, A_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O3
	.byte	quiet, A_+O3
	.byte	F_+O6, A_+O3
	.byte	quiet, A_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	E_+O5, A_+O3
	.byte	quiet, A_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	C_+O5, A_+O3
	.byte	quiet, A_+O3
	.byte	E_+O5, A_+O3
	.byte	quiet, A_+O3
	.byte	F_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O4, D_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	F_+O6, quiet
	.byte	quiet, quiet
	.byte	C_+O5, D_+O4
	.byte	quiet, D_+O4
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O4
	.byte	quiet, D_+O4
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	E_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O6, quiet
	.byte	quiet, quiet
	.byte	E_+O6, E_+O6
	.byte	quiet, E_+O6
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	quiet, D_+O3
	.byte	E_+O6, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	C_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	C_+O6, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	D_+O6, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	D_+O6, quiet
	.byte	Cs+O6, quiet
	.byte	C_+O6, As+O3
	.byte	B_+O5, As+O3
	.byte	As+O5, As+O3
	.byte	A_+O5, As+O3
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	C_+O6, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	As+O3, As+O4
	.byte	quiet, As+O4
	.byte	G_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	D_+O6, As+O3
	.byte	E_+O6, As+O3
	.byte	F_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O4, D_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	F_+O6, quiet
	.byte	quiet, quiet
	.byte	C_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	E_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	E_+O6, E_+O6
	.byte	quiet, E_+O6
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	quiet, D_+O3
	.byte	E_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O7, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	C_+O7, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O7, D_+O7
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	D_+O7, quiet
	.byte	quiet, quiet
	.byte	C_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	E_+O7, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O7, F_+O7
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	quiet, As+O3
	.byte	F_+O7, As+O3
	.byte	quiet, As+O3
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	E_+O7, E_+O7
	.byte	quiet, quiet
	.byte	C_+O7, C_+O7
	.byte	quiet, quiet
	.byte	A_+O6, A_+O6
	.byte	E_+O7, quiet
	.byte	F_+O6, F_+O6
	.byte	C_+O7, quiet
	.byte	E_+O6, E_+O6
	.byte	A_+O6, quiet
	.byte	C_+O6, C_+O6
	.byte	F_+O6, quiet
	.byte	A_+O5, A_+O5
	.byte	E_+O6, quiet
	.byte	C_+O6, C_+O6
	.byte	C_+O6, quiet
	.byte	D_+O6, G_+O3
	.byte	D_+O6, G_+O3
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	D_+O6, quiet
	.byte	D_+O6, quiet
	.byte	C_+O5, G_+O3
	.byte	C_+O5, G_+O3
	.byte	A_+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	F_+O5, F_+O5
	.byte	F_+O5, F_+O5
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, quiet
	.byte	A_+O6, quiet
	.byte	As+O6, G_+O3
	.byte	As+O6, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O5, G_+O5
	.byte	G_+O5, G_+O5
	.byte	As+O6, quiet
	.byte	As+O6, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	A_+O6, A_+O6
	.byte	A_+O6, A_+O6
	.byte	F_+O5, quiet
	.byte	F_+O5, quiet
	.byte	A_+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	A_+O6, G_+O3
	.byte	A_+O6, G_+O3
	.byte	C_+O5, C_+O5
	.byte	C_+O5, C_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	C_+O5, G_+O3
	.byte	C_+O5, G_+O3
	.byte	F_+O6, G_+O3
	.byte	F_+O6, G_+O3
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	F_+O6, quiet
	.byte	F_+O6, quiet
	.byte	G_+O5, G_+O3
	.byte	G_+O5, G_+O3
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	G_+O6, A_+O3
	.byte	G_+O6, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	G_+O6, quiet
	.byte	G_+O6, quiet
	.byte	C_+O5, A_+O3
	.byte	C_+O5, A_+O3
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	F_+O5, F_+O5
	.byte	F_+O5, F_+O5
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	quiet, A_+O3
	.byte	quiet, A_+O3
	.byte	G_+O5, G_+O5
	.byte	G_+O5, G_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	C_+O6, C_+O6
	.byte	C_+O6, C_+O6
	.byte	F_+O5, quiet
	.byte	F_+O5, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	C_+O6, A_+O3
	.byte	C_+O6, A_+O3
	.byte	C_+O5, C_+O5
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	quiet, C_+O5
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O4, quiet
	.byte	F_+O4, quiet
	.byte	A_+O3, quiet
	.byte	A_+O3, quiet
	.byte	E_+O4, A_+O3
	.byte	E_+O4, A_+O3
	.byte	F_+O4, quiet
	.byte	F_+O4, quiet
	.byte	A_+O6, A_+O3
	.byte	A_+O6, A_+O3
	.byte	As+O6, A_+O3
	.byte	As+O6, A_+O3
	.byte	C_+O7, G_+O3
	.byte	C_+O7, G_+O3
	.byte	C_+O4, G_+O3
	.byte	C_+O4, G_+O3
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	C_+O7, quiet
	.byte	C_+O7, quiet
	.byte	C_+O5, G_+O3
	.byte	C_+O5, G_+O3
	.byte	A_+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	F_+O5, F_+O5
	.byte	F_+O5, F_+O5
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	G_+O3, G_+O3
	.byte	G_+O3, G_+O3
	.byte	F_+O5, quiet
	.byte	F_+O5, quiet
	.byte	F_+O6, G_+O3
	.byte	A_+O6, G_+O3
	.byte	As+O6, G_+O3
	.byte	As+O6, G_+O3
	.byte	G_+O5, G_+O5
	.byte	G_+O5, G_+O5
	.byte	A_+O6, quiet
	.byte	A_+O6, quiet
	.byte	quiet, G_+O3
	.byte	quiet, G_+O3
	.byte	As+O6, G_+O3
	.byte	As+O6, G_+O3
	.byte	A_+O6, A_+O6
	.byte	A_+O6, A_+O6
	.byte	F_+O5, quiet
	.byte	F_+O5, quiet
	.byte	A_+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	A_+O6, G_+O3
	.byte	A_+O6, G_+O3
	.byte	C_+O5, C_+O5
	.byte	C_+O5, C_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	C_+O5, G_+O3
	.byte	C_+O5, G_+O3
	.byte	F_+O6, G_+O3
	.byte	F_+O6, G_+O3
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	F_+O6, quiet
	.byte	F_+O6, quiet
	.byte	G_+O5, G_+O3
	.byte	G_+O5, G_+O3
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	F_+O5, G_+O3
	.byte	F_+O5, G_+O3
	.byte	E_+O6, G_+O3
	.byte	F_+O6, G_+O3
	.byte	G_+O6, A_+O3
	.byte	G_+O6, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	A_+O4, A_+O4
	.byte	A_+O4, A_+O4
	.byte	G_+O6, quiet
	.byte	G_+O6, quiet
	.byte	C_+O5, A_+O3
	.byte	C_+O5, A_+O3
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	F_+O5, F_+O5
	.byte	F_+O5, F_+O5
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	A_+O3, A_+O3
	.byte	A_+O3, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	quiet, A_+O3
	.byte	quiet, A_+O3
	.byte	G_+O5, G_+O5
	.byte	G_+O5, G_+O5
	.byte	A_+O4, quiet
	.byte	A_+O4, quiet
	.byte	G_+O6, A_+O3
	.byte	G_+O6, A_+O3
	.byte	A_+O6, A_+O3
	.byte	A_+O6, A_+O3
	.byte	E_+O7, E_+O7
	.byte	E_+O7, E_+O7
	.byte	F_+O5, quiet
	.byte	F_+O5, quiet
	.byte	A_+O4, A_+O3
	.byte	A_+O4, A_+O3
	.byte	E_+O7, A_+O3
	.byte	E_+O7, A_+O3
	.byte	C_+O5, C_+O5
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	quiet, C_+O5
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	C_+O7, A_+O3
	.byte	C_+O7, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O5, A_+O3
	.byte	F_+O4, quiet
	.byte	F_+O4, quiet
	.byte	C_+O7, quiet
	.byte	C_+O7, quiet
	.byte	E_+O4, A_+O3
	.byte	E_+O4, A_+O3
	.byte	F_+O4, quiet
	.byte	F_+O4, quiet
	.byte	C_+O4, A_+O3
	.byte	C_+O4, A_+O3
	.byte	E_+O4, A_+O3
	.byte	E_+O4, A_+O3
	.byte	D_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O4, D_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	D_+O6, quiet
	.byte	quiet, quiet
	.byte	C_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	C_+O6, A_+O4
	.byte	C_+O6, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O5, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O5, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	A_+O5, quiet
	.byte	quiet, quiet
	.byte	C_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	As+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	G_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, quiet
	.byte	As+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, As+O3
	.byte	quiet, As+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, As+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	C_+O6, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	D_+O6, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O4, D_+O3
	.byte	quiet, quiet
	.byte	A_+O4, A_+O4
	.byte	quiet, A_+O4
	.byte	D_+O6, quiet
	.byte	quiet, quiet
	.byte	C_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	D_+O3, quiet
	.byte	D_+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O4, D_+O3
	.byte	A_+O4, D_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	quiet, C_+O5
	.byte	A_+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	D_+O3, D_+O3
	.byte	quiet, D_+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	C_+O6, A_+O4
	.byte	C_+O6, A_+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	A_+O5, quiet
	.byte	quiet, quiet
	.byte	G_+O5, D_+O3
	.byte	quiet, D_+O3
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	A_+O5, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, As+O3
	.byte	quiet, quiet
	.byte	As+O4, As+O4
	.byte	quiet, As+O4
	.byte	A_+O5, quiet
	.byte	quiet, quiet
	.byte	C_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O4, quiet
	.byte	quiet, quiet
	.byte	F_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	C_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O3, As+O3
	.byte	quiet, As+O3
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	As+O5, G_+O5
	.byte	quiet, G_+O5
	.byte	A_+O5, F_+O5
	.byte	quiet, F_+O5
	.byte	G_+O5, As+O3
	.byte	quiet, As+O3
	.byte	As+O3, quiet
	.byte	As+O3, quiet
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	F_+O5, quiet
	.byte	quiet, quiet
	.byte	As+O4, As+O3
	.byte	As+O4, As+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	C_+O5, C_+O5
	.byte	C_+O5, C_+O5
	.byte	As+O4, quiet
	.byte	As+O4, quiet
	.byte	F_+O5, As+O3
	.byte	F_+O5, As+O3
	.byte	C_+O5, quiet
	.byte	C_+O5, quiet
	.byte	As+O3, As+O3
	.byte	As+O3, As+O3
	.byte	F_+O5, quiet
	.byte	F_+O5, quiet
	.byte	As+O4, As+O4
	.byte	As+O4, As+O4
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	G_+O5, As+O3
	.byte	G_+O5, As+O3
	.byte	As+O4, quiet
	.byte	As+O4, quiet
	.byte	C_+O6, As+O3
	.byte	C_+O6, As+O3
	.byte	As+O3, As+O3
	.byte	As+O3, As+O3
	.byte	D_+O5, G_+O3
	.byte	D_+O5, G_+O3
	.byte	G_+O4, G_+O4
	.byte	G_+O4, G_+O4
	.byte	Gs+O4, A_+O4
	.byte	D_+O5, A_+O4
	.byte	A_+O4, A_+O4
	.byte	G_+O4, A_+O4
	.byte	C_+O5, G_+O3
	.byte	Gs+O4, G_+O3
	.byte	F_+O5, F_+O5
	.byte	A_+O4, F_+O5
	.byte	Gs+O5, Gs+O5
	.byte	C_+O5, Gs+O5
	.byte	A_+O5, A_+O5
	.byte	F_+O5, A_+O5
	.byte	G_+O5, G_+O3
	.byte	Gs+O5, G_+O3
	.byte	D_+O6, D_+O6
	.byte	A_+O5, D_+O6
	.byte	C_+O6, G_+O3
	.byte	G_+O5, G_+O3
	.byte	A_+O5, A_+O5
	.byte	D_+O6, A_+O5
	.byte	F_+O6, F_+O6
	.byte	C_+O6, F_+O6
	.byte	C_+O6, C_+O6
	.byte	A_+O5, C_+O6
	.byte	D_+O6, G_+O3
	.byte	F_+O6, G_+O3
	.byte	A_+O5, A_+O5
	.byte	C_+O6, A_+O5
	.byte	Gs+O5, Gs+O5
	.byte	D_+O6, Gs+O5
	.byte	G_+O5, G_+O5
	.byte	A_+O5, G_+O5
	.byte	F_+O5, G_+O3
	.byte	Gs+O5, G_+O3
	.byte	D_+O5, D_+O5
	.byte	G_+O5, D_+O5
	.byte	Cs+O5, Cs+O5
	.byte	F_+O5, Cs+O5
	.byte	C_+O5, C_+O5
	.byte	D_+O5, C_+O5
	.byte	A_+O4, G_+O3
	.byte	Cs+O5, G_+O3
	.byte	G_+O4, G_+O4
	.byte	C_+O5, G_+O4
	.byte	Gs+O4, G_+O3
	.byte	A_+O4, G_+O3
	.byte	F_+O4, F_+O4
	.byte	G_+O4, F_+O4
	.byte	G_+O4, G_+O4
	.byte	Gs+O4, G_+O4
	.byte	D_+O4, D_+O4
	.byte	F_+O4, D_+O4
	.byte	F_+O4, G_+O3
	.byte	G_+O4, G_+O3
	.byte	G_+O4, G_+O4
	.byte	D_+O4, G_+O4
	.byte	Gs+O4, G_+O3
	.byte	F_+O4, G_+O3
	.byte	F_+O4, F_+O4
	.byte	G_+O4, F_+O4
	.byte	G_+O5, A_+O3
	.byte	Gs+O4, A_+O3
	.byte	D_+O5, D_+O5
	.byte	F_+O4, D_+O5
	.byte	Gs+O5, Gs+O5
	.byte	G_+O5, Gs+O5
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	A_+O5, A_+O3
	.byte	Gs+O5, A_+O3
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	C_+O6, C_+O6
	.byte	A_+O5, C_+O6
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	Cs+O6, A_+O3
	.byte	C_+O6, A_+O3
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	D_+O6, D_+O6
	.byte	Cs+O6, D_+O6
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	F_+O6, F_+O6
	.byte	D_+O6, F_+O6
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	G_+O6, A_+O3
	.byte	F_+O6, A_+O3
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	Gs+O6, Gs+O6
	.byte	G_+O6, Gs+O6
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	A_+O6, A_+O3
	.byte	Gs+O6, A_+O3
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	C_+O7, C_+O7
	.byte	A_+O6, C_+O7
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	Cs+O7, A_+O3
	.byte	C_+O7, A_+O3
	.byte	D_+O5, D_+O5
	.byte	D_+O5, D_+O5
	.byte	D_+O7, A_+O3
	.byte	Cs+O7, A_+O3
	.byte	A_+O6, A_+O6
	.byte	D_+O5, A_+O6
	.byte	F_+O6, F_+O6
	.byte	D_+O7, F_+O6
	.byte	D_+O6, D_+O6
	.byte	A_+O6, D_+O6
	.byte	C_+O7, A_+O3
	.byte	F_+O6, A_+O3
	.byte	A_+O6, A_+O6
	.byte	D_+O6, A_+O6
	.byte	F_+O6, F_+O6
	.byte	C_+O7, F_+O6
	.byte	C_+O6, C_+O6
	.byte	A_+O6, C_+O6
	.byte	D_+O6, G_+O3
	.byte	quiet, G_+O3
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	E_+O6, E_+O6
	.byte	quiet, E_+O6
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	F_+O6, G_+O3
	.byte	quiet, G_+O3
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	G_+O6, G_+O6
	.byte	quiet, G_+O6
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	Gs+O6, G_+O3
	.byte	quiet, G_+O3
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	A_+O6, G_+O3
	.byte	quiet, G_+O3
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	C_+O7, C_+O7
	.byte	quiet, C_+O7
	.byte	A_+O5, A_+O5
	.byte	quiet, A_+O5
	.byte	D_+O7, G_+O3
	.byte	quiet, G_+O3
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	E_+O7, E_+O7
	.byte	quiet, E_+O7
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	C_+O7, G_+O3
	.byte	quiet, G_+O3
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	D_+O7, D_+O7
	.byte	quiet, D_+O7
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	A_+O6, G_+O3
	.byte	quiet, G_+O3
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	F_+O7, G_+O3
	.byte	quiet, G_+O3
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	G_+O6, G_+O6
	.byte	quiet, G_+O6
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	E_+O7, G_+O3
	.byte	quiet, G_+O3
	.byte	D_+O6, D_+O6
	.byte	quiet, D_+O6
	.byte	D_+O7, G_+O3
	.byte	quiet, G_+O3
	.byte	C_+O7, C_+O6
	.byte	quiet, C_+O6
	.byte	D_+O6, A_+O3
	.byte	quiet, A_+O3
	.byte	C_+O7, C_+O6
	.byte	quiet, C_+O6
	.byte	D_+O6, D_+O5
	.byte	quiet, quiet
	.byte	D_+O7, D_+O6
	.byte	quiet, quiet
	.byte	D_+O6, A_+O3
	.byte	quiet, A_+O3
	.byte	C_+O7, C_+O6
	.byte	quiet, quiet
	.byte	C_+O7, C_+O6
	.byte	quiet, quiet
	.byte	D_+O6, D_+O5
	.byte	quiet, quiet
	.byte	C_+O7, A_+O3
	.byte	quiet, A_+O3
	.byte	D_+O6, D_+O5
	.byte	quiet, quiet
	.byte	F_+O7, A_+O3
	.byte	quiet, A_+O3
	.byte	quiet, quiet
	.byte	quiet, quiet
	.byte	D_+O7, D_+O5
	.byte	C_+O7, C_+O5
	.byte	A_+O6, A_+O4
	.byte	Gs+O6, Gs+O4
	.byte	G_+O6, G_+O4
	.byte	F_+O6, F_+O4
	.byte	D_+O6, D_+O4
	.byte	Cs+O6, Cs+O4
	.byte	C_+O6, C_+O4
	.byte	A_+O5, A_+O3
	.byte	Gs+O5, Gs+O3
	.byte	G_+O5, G_+O3
	.byte	F_+O7, F_+O7
	.byte	F_+O7, F_+O7
	.byte	E_+O7, A_+O3
	.byte	A_+O6, A_+O3
	.byte	A_+O6, A_+O6
	.byte	F_+O7, A_+O6
	.byte	E_+O7, A_+O3
	.byte	E_+O7, A_+O3
	.byte	D_+O7, D_+O7
	.byte	A_+O6, quiet
	.byte	C_+O7, C_+O7
	.byte	E_+O7, quiet
	.byte	A_+O6, A_+O6
	.byte	D_+O7, A_+O6
	.byte	F_+O6, A_+O3
	.byte	C_+O7, A_+O3
	.byte	E_+O6, E_+O6
	.byte	A_+O6, E_+O6
	.byte	C_+O6, A_+O3
	.byte	F_+O6, A_+O3
	.byte	A_+O4, A_+O5
	.byte	Gs+O4, Gs+O5
	.byte	G_+O4, G_+O5
	.byte	Fs+O4, Fs+O5
	.byte	F_+O4, F_+O5
	.byte	E_+O4, E_+O5
	.byte	Ds+O4, Ds+O5
	.byte	D_+O4, D_+O5

endzix	.word	$ffff	;signal loop
